language: rust
sudo: false
rust:
  - stable
  - beta
addons:
  apt:
    packages:
      - liblzma-dev
script:
  - cargo build --verbose
  - cargo package --verbose
  - cargo test --verbose
  - cargo doc --verbose
